FROM nginx:latest
MAINTAINER josiah.peters@alertsense.com

ADD default.conf /etc/nginx/conf.d/default.conf
ADD grafana-nginx.conf /etc/nginx/conf.d/grafana.conf
ADD influxdb-nginx.conf /etc/nginx/conf.d/influxdb.conf
#ADD server.crt /etc/nginx/ssl/server.crt
#ADD server.key /etc/nginx/ssl/server.key
